version: '3.8'

services:
  midaz-mcp-server:
    build: .
    image: midaz/mcp-server:latest
    container_name: midaz-mcp-server
    restart: unless-stopped
    environment:
      # Backend configuration
      - MIDAZ_ONBOARDING_URL=${MIDAZ_ONBOARDING_URL:-http://host.docker.internal:3000}
      - MIDAZ_TRANSACTION_URL=${MIDAZ_TRANSACTION_URL:-http://host.docker.internal:3001}
      - MIDAZ_API_KEY=${MIDAZ_API_KEY:-}
      - MIDAZ_USE_STUBS=${MIDAZ_USE_STUBS:-true}
      - MIDAZ_DOCS_URL=${MIDAZ_DOCS_URL:-https://docs.lerian.studio}
      # Node environment
      - NODE_ENV=production
    volumes:
      # Mount logs directory for audit logs
      - ./logs:/app/logs
      # Mount config file if it exists
      - ./midaz-mcp-config.json:/app/midaz-mcp-config.json:ro
    # For stdio communication
    stdin_open: true
    tty: true
    # Security settings
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    networks:
      - midaz-network

  # Example of running with Claude Desktop via socat
  # This creates a bridge between network socket and stdio
  midaz-mcp-bridge:
    image: alpine/socat:latest
    container_name: midaz-mcp-bridge
    restart: unless-stopped
    command: TCP-LISTEN:3330,fork,reuseaddr EXEC:'docker exec -i midaz-mcp-server node dist/index.js'
    ports:
      - "3330:3330"
    depends_on:
      - midaz-mcp-server
    networks:
      - midaz-network

networks:
  midaz-network:
    driver: bridge